### PR TITLE
disable telemetry API

### PR DESCRIPTION
**Pull request by naushniki**
* move starter arguments that must be applied conditionally based on version to one place
* disable telemetry API

### CODE REVIEW

**Review by dothebart — APPROVED** [review]

**Comment by naushniki** [comment]
https://jenkins.arangodb.biz/view/RTA/job/Upgrade-3.9-to-3.10.Linux/1113/

**Comment by naushniki** [comment]
https://jenkins.arangodb.biz/view/RTA/job/Test-3.11.Linux/84/

**Comment by naushniki** [comment]
https://jenkins.arangodb.biz/view/RTA/job/Upgrade-3.10-to-3.11.Windows/145

**Comment by naushniki** [comment]
https://jenkins.arangodb.biz/view/RTA/job/Upgrade-3.9-to-3.10.Linux/1115/
https://jenkins.arangodb.biz/view/RTA/job/Test-3.11.Linux/86/
https://jenkins.arangodb.biz/view/RTA/job/Upgrade-3.10-to-3.11.Windows/148/

**Comment by naushniki** [comment]
https://jenkins.arangodb.biz/view/RTA/job/Upgrade-3.10-to-3.11.Windows/151/

**Pull request merged**
